[package]
name = "vinx-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ed25519-dalek = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
blake3 = { workspace = true }
bech32 = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
borsh = { workspace = true }
blst = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
