[package]
name = "vinx-node"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "vinx-node"
path = "src/main.rs"

[dependencies]
vinx-crypto = { path = "../vinx-crypto" }
vinx-core = { path = "../vinx-core" }
vinx-state = { path = "../vinx-state" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bincode = { workspace = true }
libp2p = { version = "0.54", features = ["gossipsub", "noise", "tcp", "yamux", "tokio", "identify", "mdns", "macros", "quic"] }
borsh = { workspace = true }
rayon = { workspace = true }
futures = "0.3"
toml = "0.8"
clap = { version = "4", features = ["derive"] }
url = "2"
reqwest = { version = "0.12", features = ["json"] }
tokio-stream = { version = "0.1", features = ["sync"] }
redb = "2"
bloomfilter = "1"
zstd = { workspace = true }
lru = "0.12"
ahash = { version = "0.8", features = ["serde"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { workspace = true }
