[package]
name = "vinx-node"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "vinx-node"
path = "src/main.rs"

[dependencies]
vinx-crypto = { path = "../vinx-crypto" }
vinx-core = { path = "../vinx-core" }
vinx-state = { path = "../vinx-state" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { workspace = true }
