[package]
name = "vinx-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
vinx-crypto = { path = "../vinx-crypto" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
bincode = { workspace = true }
